### ISSUE TITLE
Direct Message compile error

### ISSUE THREAD

**Issue by John-Vahanyan** [Twitter4J/Twitter4J#299]
Compilation failure: 
 ******\twitter4j-core\src\main\java\twitter4j\DirectMessage.java:[62,17] error: method getQuickReplies() is already defined in interface DirectMessage 
******\twitter4j-core\src\main\java\twitter4j\DirectMessage.java:[69,11] error: method getQuickReplyResponse() is already defined in interface DirectMessage

**Comment by yusuke** [comment]
fixed. thanks
