### ISSUE TITLE
Put localization in a Tweet

### ISSUE THREAD

**Issue by adriens** [Twitter4J/Twitter4J#317]
Hi, I'd like to put localization in a Tweet (long,lat) : how can this be done please ? 🙏

**Comment by adriens** [comment]
How to do this with code please ?

https://help.twitter.com/en/using-twitter/tweet-location

**Comment by estaine** [comment]
@adriens If you want to append a location to your tweet, you should try something like this:
`
Twitter twitter = TwitterFactory.getSingleton();
StatusUpdate tweet = new StatusUpdate("Hey! I'm tweeting from the Stonehenge!");
GeoLocation stonehenge = new GeoLocation(51.1789, -1.8262);
tweet.setLocation(stonehenge);
Status status = twitter.updateStatus(latestStatus);
`

**Comment by adriens** [comment]
WOW, thank you very much @estaine : THIS IS EXACTLY what I was looking for !!! 🎆

**Comment by adriens** [comment]
Just to let you knwo, here is what I could achieve thanks to your library : 
https://www.linkedin.com/pulse/let-twitter-bots-tell-you-when-can-go-swim-adrien-sales/

Have a great week and thanks to mainain this very easy to use library. 👍
