### ISSUE TITLE
missing GET accounts/:account_id/tweet/preview

### ISSUE THREAD

**Issue by jonnytest1** [Twitter4J/Twitter4J#323]
I might have missed it but I searched through the git repo and didnt find an implementation of this API:

missing GET accounts/:account_id/tweet/preview
https://developer.twitter.com/en/docs/ads/creatives/api-reference/tweets

**Comment by igorbrigadir** [comment]
This is the Ads API, which is separate - check out https://github.com/sprinklr-inc/twitter4j-ads instead
