### ISSUE TITLE
Twitter ids no longer fit in a long

### ISSUE THREAD

**Issue by afcruzs** [Twitter4J/Twitter4J#326]
The `FilterQuery` class receives multiple `long` parameters in the follow method which represent the user id. New account ids no longer fit in longs. An example: http://gettwitterid.com/?user_name=geoffreyhinton&submit=GET+USER+ID

I propose to include an overriden version of the follow method which receives strings instead. I'm happy to help.

**Comment by igorbrigadir** [comment]
This doesn't seem right - that id is `1084212657761148928` which is well within the range of a `long` integer in java.

What's the exact error you're seeing and how are you using FilterQuery?

**Comment by afcruzs** [comment]
Never mind... I didn't check against the max long value, it indeed fits, but needs to be declared as `1084212657761148928l` (with the l at the end).
