### ISSUE TITLE
Adding GeoLocation to StatusUpdate not working

### ISSUE THREAD

**Issue by nuclearfog** [Twitter4J/Twitter4J#336]
After uploading a tweet
```java
StatusUpdate mStatus = new StatusUpdate("tweet geolocation");
mStatus.setLocation(new GeoLocation(location.getLatitude(), location.getLongitude()));
Status status = twitter.updateStatus(mStatus);
GeoLocation geoLocation = status.getGeoLocation(); // null
```
the GeolLocation of the tweet is always null!

**Comment by moko256** [comment]
Hello,

Did you allow Twitter to add location information to tweets? If didn't, it will not be added.
It is disabled by default. You can turn on in "Settings > Privacy and safety > Location information > Add location information to my Tweets".

Docs: [Tweet location FAQs](https://help.twitter.com/en/safety-and-security/tweet-location-settings)

**Comment by nuclearfog** [comment]
Thank you! It's working now!
