### ISSUE TITLE
Plans for the next Twitter API

### ISSUE THREAD

**Issue by andypiper** [Twitter4J/Twitter4J#343]
Yusuke! Hello from Twitter Developer Relations! we know how pivotal you have been in developer interest in the Twitter API and we want to thank you for Twitter4J, surely one of the more important libraries that supports apps that talk to Twitter.

We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs to Twitter4J. We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we list Twitter4J on our developer libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the Java community. Thank you all, again!

**Comment by andypiper** [comment]
Just following up here!

We’ve announced plans and roadmap for v2 of the Twitter API, coming very soon.

Let us know if you have questions and we thank you for the continued support for the Java community!

**Comment by takke** [comment]
Hi Andy.

I'm one of the contributors to Twitter4J.
I've been using the new labs API since it was released.
So I've tried to create new additional package for Twitter4J to support API v2.

Check this out: 
https://github.com/takke/twitter4j-v2

**Comment by andypiper** [comment]
This is great news, thank you, I think you’ve been in touch with one of my friends Suhem as well :-) I will make sure to update what is happening in our library catalog :-D

**Comment by yusuke** [comment]
Sorry for my late reply.
I'm now restoring the CI environment so that I can move on.

**Comment by suyashjoshi** [comment]
Any updates on supporting the Twitter API v2 with this project?

**Comment by suyashjoshi** [comment]
> Hi Andy.
> 
> I'm one of the contributors to Twitter4J.
> I've been using the new labs API since it was released.
> So I've tried to create new additional package for Twitter4J to support API v2.
> 
> Check this out:
> https://github.com/takke/twitter4j-v2

this looks nice, checking it out now. thanks!

**Comment by rzo1** [comment]
@yusuke Please give us a ping, if you need assistance with implementing the new API v2 features in twitter4j.

For now, we have implemented our own adapter library based on the original twitter4j API for search and streaming endpoints (which is quite difficult as the original library uses an extensive amount of `final` modifiers in the class hierachy...) ...

**Comment by mayank-mundhra-2012** [comment]
Big fan of Twitter4J. Used it a few years back for an academic learning project. Would love to see it live and running. Considering using it for a new project of mine that will happen in 3-4 months. Please keep the project live and chugging.

**Comment by rzo1** [comment]
Any updates @yusuke ?

**Comment by seinecle** [comment]
New Twitter API v2 Java SDK supported by Twitter:
https://github.com/twitterdev/twitter-api-java-sdk
