### ISSUE TITLE
getDirectMessages()

### ISSUE THREAD

**Issue by jbw80** [Twitter4J/Twitter4J#348]
Is receiving DMs completely broken for now?

**Comment by darkfrog26** [comment]
It's working for me except for trying to receive them via streaming.

**Comment by jbw80** [comment]
Which method are you using? .getDirectMessages() or anything I've found so far only returns "Not Implemented"

**Comment by darkfrog26** [comment]
`twitter.directMessages().getDirectMessages(50)`

**Comment by jbw80** [comment]
ah, i must be using a different build than yours. twitter.directMessages() takes an argument and can't be void.

**Comment by darkfrog26** [comment]
Using `4.0.7`, which is the latest version.

**Comment by jbw80** [comment]
same one I'm using.. weird. oh well, thanks for the help =)

**Comment by darkfrog26** [comment]
I'm guessing you're not establishing your `Twitter` instance properly then.

Take a look at the guide: http://twitter4j.org/en/code-examples.html

**Comment by jbw80** [comment]
evidently not, i was using TwitterFactory.getInstance() not TwitterFactory.getSingleton()
thanks again

**Comment by darkfrog26** [comment]
I use `getInstance(accessToken)`, so that shouldn't be your problem. Oh, and looking at the code, if you're using a `Twitter` instance, there is only one `directMessage` method and it takes no arguments.

**Comment by jbw80** [comment]
Cool, I'll poke around a bit more and close this since it's a newbie issue and not an actual issue.
