### ISSUE TITLE
Get URL of tweet from stream

### ISSUE THREAD

**Issue by djKooks** [Twitter4J/Twitter4J#354]
Hello,
I'm testing tweet stream function as below:
```
TwitterStream twitterStream = new TwitterStreamFactory(configurationBuilder.build()).getInstance();
twitterStream.addListener(new StatusListener() {

            @Override
            public void onStatus(Status status) { ... }
...
```
but depend on document of `Status`, I cannot find the direct url link of received tweet. How can I get it?

**Comment by yusuke** [comment]
"https://twitter.com/"+status.getUser().getScreenName()+"/"+status.getId(), is the perm link of the tweet.
