### ISSUE TITLE
How to create a Bot

### ISSUE THREAD

**Issue by Phill030** [Twitter4J/Twitter4J#360]
Hello, i wanted to create a TwitterBot but i dont know how do i set everything up. since more than 3 months i cant use "ConfigurationBuilder cb = new ConfigurationBuilder()" and almost everything is not working for me.
Can someone tell me how i create a bot?
thx

**Comment by eos1d3** [comment]
This repo is dead. I think `ConfigurationBuilder `can still work. Many other API endpoints are obsoleted. 

Twitter has updated its API for years while this repo never changes since 3 years ago.

**Comment by Philipinho** [comment]
The library still works great. I use it for my projects.

You try the below code.
Make sure you install the library properly.

```
public class TwitterTest {

   import twitter4j.*;
 
   private static  TwitterFactory tf = new TwitterFactory(conf());
   private static Twitter twitter = tf.getInstance();

   private static Configuration conf() {
        ConfigurationBuilder cb = new ConfigurationBuilder();
        cb.setDebugEnabled(true)
                .setOAuthConsumerKey("xxxxxxxxxxx")
                .setOAuthConsumerSecret("xxxxxxxxxxx")
                .setOAuthAccessToken("xxxxxx)
                .setOAuthAccessTokenSecret("xxxxx");
        return cb.build();
    }
    
   public static void main (String[] args){
      twitter.verifyCredentials();
   }
}
```
