### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [Twitter4J/Twitter4J#387]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `twitter4j-core\pom.xml`, `commons-logging:commons-logging-api` scope should be `compile`  instead of `provided`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by yusuke** [comment]
Thanks.
It's now declared as compileOnly in build.gradle.
