### ISSUE TITLE
No way to set RequestToken for OAuth 1.0a

### ISSUE THREAD

**Issue by tkawachi** [Twitter4J/Twitter4J#395]
Since Twitter4J 4.1.0, RequestToken constructors no longer have access modifiers, so RequestToken instances can no longer be created from user code. As a result, there seems to be no way to set RequestToken for OAuthAuthorization.

Previously, the following code was used to set the RequestToken and obtain the AccessToken.

```
Twitter twitter = new TwitterFactory(new ConfigurationBuilder().build()).getInstance();
RequestToken requestToken = new RequestToken(token, secret); // ← can't create an instance since 4.1.0
twitter.getOAuthAccessToken(requestToken, oAuthVerifier);
```

**Comment by yusuke** [comment]
Since 4.1.0, Twitter4J is fully immutable. There is no way to mutate object states.

You can instantiate a new Twitter instance with the newly created access token thru builder as follow:
```java
Twitter twitter = Twitter.newBuilder().oAuthConsumer(consumerKey, consumerSecret)
                .oAuthAccessToken(accessToken).build();
```

**Comment by tkawachi** [comment]
It seems that what specified as `.oAuthAccessToken()` is [set as an `AccessToken`](https://github.com/Twitter4J/Twitter4J/blob/d899f3f6a384c197f9e198fde5d966248ee30971/twitter4j-core/src/main/java/twitter4j/OAuthAuthorization.java#L93).
What should I do if I want to set a `RequestToken`?

**Comment by yusuke** [comment]
[You can acquire AccessToken via getOAuthAccessToken()](https://twitter4j.org/code-examples#oauth)

**Comment by tkawachi** [comment]
Let me explain a little more.

I am trying to implement the 3-legged OAuth flow described at https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens.
When requesting POST oauth/access_token, which corresponds `getOAuthAccessToken()` in Step 3, I need a RequestToken instance. However, since Step 1 and Step 3 are executed by different HTTP requests, RequestToken instance obtained in Step 1 is not in memory in Step 3. I think it will not be able to complete the flow unless I can somehow create an instance of RequestToken from the `oauth_token` and `oauth_token_secret` strings saved in Step 1.

I am not very familiar with this, so please let me know if I have misunderstood the flow.

**Comment by yusuke** [comment]
RequestToken implements Serializable. So you can store the RequestToken in session scope for the later reference.

**Comment by tkawachi** [comment]
I see. Thank you for the reply.
